'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, BarChart3, Bell, BusFront, Check, CircleHelp, CreditCard, FileCheck2, Route, Send, Settings2, Users, WalletCards } from 'lucide-react';
import { useDriverEarnings, useDriverTrip, useDriverTrips } from '@/lib/hooks/useDriverQueries';
import { api } from '@/lib/api/client';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

function PageHeading({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) {
  return <div className="mb-5 flex items-start justify-between gap-3"><div><Link href="/driver/dashboard" className="mb-2 inline-flex items-center gap-1 text-xs font-bold text-emerald-600 hover:text-emerald-700"><ArrowLeft className="size-3.5" /> Dashboard</Link><h1 className="text-xl font-extrabold text-slate-900">{title}</h1><p className="mt-1 text-sm text-slate-500">{description}</p></div>{action}</div>;
}

const darkCard = 'border-slate-200 bg-white text-slate-900 shadow-sm';

export function DriverEarningsPage() {
  const { data, isLoading } = useDriverEarnings('week');
  const [withdrawn, setWithdrawn] = useState(false);
  const total = data?.totalEarnings || 0;
  const trips = data?.totalTrips || 0;
  return <div><PageHeading title="Earnings & wallet" description="Monitor trip earnings, payout status, and incentive progress." action={<Button size="sm" disabled={!total || withdrawn} onClick={() => setWithdrawn(true)}>{withdrawn ? <><Check className="size-3.5" /> Requested</> : 'Withdraw payout'}</Button>} />
    <div className="grid gap-3 sm:grid-cols-3"><Card className={darkCard}><CardContent className="p-4"><WalletCards className="size-5 text-emerald-400" /><p className="mt-4 text-xs font-bold uppercase tracking-wide text-slate-400">This week</p><p className="mt-1 text-2xl font-extrabold">{isLoading ? '—' : `₹${total.toLocaleString('en-IN')}`}</p></CardContent></Card><Card className={darkCard}><CardContent className="p-4"><Route className="size-5 text-blue-400" /><p className="mt-4 text-xs font-bold uppercase tracking-wide text-slate-400">Completed trips</p><p className="mt-1 text-2xl font-extrabold">{isLoading ? '—' : trips}</p></CardContent></Card><Card className={darkCard}><CardContent className="p-4"><CreditCard className="size-5 text-amber-400" /><p className="mt-4 text-xs font-bold uppercase tracking-wide text-slate-400">Pending payout</p><p className="mt-1 text-2xl font-extrabold">₹2,840</p></CardContent></Card></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-[1.4fr_1fr]"><Card className={darkCard}><CardHeader><CardTitle>Weekly earning trend</CardTitle><CardDescription className="text-slate-400">A comparison of your daily completed-trip earnings.</CardDescription></CardHeader><CardContent><div className="flex h-40 items-end justify-between gap-2 border-b border-white/10 pb-2">{[38, 62, 47, 78, 55, 86, 66].map((height, index) => <div key={index} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t bg-emerald-500/80" style={{ height: `${height}%` }} /><span className="text-[10px] text-slate-500">{['M','T','W','T','F','S','S'][index]}</span></div>)}</div><div className="mt-5 space-y-3">{['Trip settlement · TRQ-9916', 'Referral commission · TQDRV98', 'Fuel efficiency incentive'].map((item, index) => <div key={item} className="flex items-center justify-between text-sm"><span className="text-slate-300">{item}</span><span className="font-bold text-emerald-400">+ ₹{[840, 150, 300][index]}</span></div>)}</div></CardContent></Card><Card className={darkCard}><CardHeader><CardTitle>Daily incentives</CardTitle></CardHeader><CardContent className="space-y-5">{[{ label: 'Complete 6 rides', current: 4, target: 6, reward: '₹200' }, { label: 'Stay online 8 hours', current: 5.5, target: 8, reward: '₹150' }].map((target) => <div key={target.label}><div className="mb-2 flex justify-between text-xs"><span className="font-bold text-slate-200">{target.label}</span><span className="text-emerald-400">{target.reward}</span></div><Progress value={(target.current / target.target) * 100} className="bg-white/10" /><p className="mt-1 text-xs text-slate-500">{target.current} of {target.target}</p></div>)}</CardContent></Card></div>
  </div>;
}

export function DriverRoutesPage() {
  const { data } = useDriverTrips(1, 50);
  const activeTrip = useMemo(() => data?.data?.find((trip) => trip.status === 'IN_PROGRESS' || trip.status === 'SCHEDULED'), [data]);
  const stops = activeTrip?.route?.stops || activeTrip?.routeId?.stops || [];
  return <div><PageHeading title="Route navigation" description="Live corridor telemetry, stops, and passenger handoffs." action={<Badge variant="default">GPS active</Badge>} />
    <Card className={`${darkCard} overflow-hidden`}><CardContent className="p-0"><div className="relative min-h-60 bg-[radial-gradient(circle_at_25%_30%,rgba(34,197,94,0.25),transparent_25%),radial-gradient(circle_at_75%_65%,rgba(59,130,246,0.22),transparent_30%),#0f172a] p-5"><div className="absolute inset-x-7 top-1/2 h-1 -rotate-12 bg-emerald-400/70" /><div className="relative flex h-48 flex-col justify-between"><div className="flex justify-between gap-3"><div className="rounded-lg border border-emerald-400/50 bg-slate-950/85 p-3"><p className="text-[10px] font-bold text-emerald-400">CURRENT STOP</p><p className="text-sm font-bold">HSR Layout Sector 1</p></div><div className="rounded-lg border border-blue-400/50 bg-slate-950/85 p-3 text-right"><p className="text-[10px] font-bold text-blue-400">NEXT TARGET</p><p className="text-sm font-bold">Agara Lake Flyover</p></div></div><div className="rounded-xl bg-slate-950/85 p-3 backdrop-blur"><div className="flex justify-between text-xs"><span className="text-slate-300">Trip progress</span><span className="font-bold text-emerald-400">45% · 22 min ETA</span></div><Progress value={45} className="mt-2 bg-white/10" /></div></div></div></CardContent></Card>
    <Card className={`mt-4 ${darkCard}`}><CardHeader><CardTitle>Route sequence & stops</CardTitle><CardDescription className="text-slate-400">{activeTrip?.route?.name || activeTrip?.routeId?.name || 'No current route is assigned.'}</CardDescription></CardHeader><CardContent className="space-y-3">{stops.length ? stops.map((stop: { stopName?: string; name?: string; sequenceOrder?: number }, index: number) => <div key={stop.sequenceOrder || index} className="flex gap-3 rounded-xl border border-white/10 p-3"><div className={`mt-1 size-2.5 rounded-full ${index === 0 ? 'bg-emerald-400' : 'bg-blue-400'}`} /><div><p className="text-xs font-bold text-slate-500">STOP {index + 1}</p><p className="text-sm font-bold">{stop.stopName || stop.name || 'Route stop'}</p></div></div>) : <p className="text-sm text-slate-400">Your assigned stops will appear here after dispatch creates a trip.</p>}</CardContent></Card>
  </div>;
}

interface DriverNotification { _id: string; title: string; message: string; createdAt?: string; isRead?: boolean; isDeleted?: boolean; }

export function DriverNotificationsPage() {
  const queryClient = useQueryClient();
  const [filter, setFilter] = useState('ALL');
  const notifications = useQuery({ queryKey: ['driver', 'notifications'], queryFn: () => api.get<DriverNotification[]>('/notifications'), select: (response) => response.data.filter((item) => !item.isDeleted) });
  const markRead = useMutation({ mutationFn: () => api.put('/notifications/read', { ids: [] }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['driver', 'notifications'] }) });
  const remove = useMutation({ mutationFn: (id: string) => api.delete(`/notifications/${id}`), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['driver', 'notifications'] }) });
  const all = notifications.data || [];
  const displayed = filter === 'UNREAD' ? all.filter((item) => !item.isRead) : all;
  return <div><PageHeading title="Notifications center" description="Live trip, payout, and operations updates from your driver account." action={<Button variant="dark" size="sm" onClick={() => markRead.mutate()} disabled={markRead.isPending}>Mark all read</Button>} />
    <Tabs defaultValue="ALL" onValueChange={setFilter}><TabsList className="w-full justify-start overflow-x-auto bg-white/10"><TabsTrigger value="ALL">All alerts</TabsTrigger><TabsTrigger value="UNREAD">Unread</TabsTrigger></TabsList><TabsContent value={filter} className="space-y-3">{notifications.isLoading ? <p className="py-8 text-center text-sm text-slate-400">Loading notifications…</p> : notifications.isError ? <p className="py-8 text-center text-sm text-red-400">Unable to load notifications.</p> : displayed.map((item) => <Card key={item._id} className={`${darkCard} ${!item.isRead ? 'border-emerald-400/40 bg-emerald-400/[0.06]' : ''}`}><CardContent className="flex gap-3 p-4"><Bell className="mt-0.5 size-5 shrink-0 text-emerald-400" /><div className="flex-1"><div className="flex justify-between gap-2"><p className="text-sm font-bold">{item.title}</p>{!item.isRead && <span className="mt-1 size-2 rounded-full bg-emerald-400" />}</div><p className="mt-1 text-xs leading-5 text-slate-400">{item.message}</p><p className="mt-2 text-[10px] text-slate-500">{item.createdAt ? new Date(item.createdAt).toLocaleString('en-IN') : ''}</p></div><button aria-label="Delete notification" onClick={() => remove.mutate(item._id)} className="text-xs font-bold text-red-400">Delete</button></CardContent></Card>)}{!notifications.isLoading && !displayed.length && <p className="py-8 text-center text-sm text-slate-400">No alerts in this view.</p>}</TabsContent></Tabs>
  </div>;
}

export function DriverAnalyticsPage() {
  const { data, isLoading } = useDriverTrips(1, 50, 'week');
  const completed = data?.data?.filter((trip) => trip.status === 'COMPLETED').length || 0;
  const total = data?.data?.length || 0;
  const rate = total ? Math.round((completed / total) * 100) : 0;
  return <div><PageHeading title="Performance analytics" description="A weekly view of reliability, time on duty, and trip completion." /><div className="grid gap-3 sm:grid-cols-3">{[{ label: 'Completion rate', value: isLoading ? '—' : `${rate}%`, icon: FileCheck2 }, { label: 'Trips allocated', value: isLoading ? '—' : total, icon: Route }, { label: 'Duty hours', value: '32.5h', icon: BarChart3 }].map((metric) => <Card key={metric.label} className={darkCard}><CardContent className="p-4"><metric.icon className="size-5 text-emerald-400" /><p className="mt-4 text-xs font-bold uppercase tracking-wide text-slate-400">{metric.label}</p><p className="mt-1 text-2xl font-extrabold">{metric.value}</p></CardContent></Card>)}</div><Card className={`mt-4 ${darkCard}`}><CardHeader><CardTitle>Service quality</CardTitle><CardDescription className="text-slate-400">Keep a high on-time rate to unlock more incentives.</CardDescription></CardHeader><CardContent className="space-y-5">{[{ label: 'On-time pickups', value: 92 }, { label: 'Manifest accuracy', value: 98 }, { label: 'Passenger rating', value: 96 }].map((metric) => <div key={metric.label}><div className="mb-2 flex justify-between text-sm"><span>{metric.label}</span><strong className="text-emerald-400">{metric.value}%</strong></div><Progress value={metric.value} className="bg-white/10" /></div>)}</CardContent></Card></div>;
}

export function DriverManagementPage({ section }: { section: 'vehicle' | 'documents' | 'settings' | 'support' }) {
  const [saved, setSaved] = useState(false);
  const config = { vehicle: { icon: BusFront, title: 'Vehicle details', description: 'Keep vehicle capacity and registration information current.' }, documents: { icon: FileCheck2, title: 'Documents', description: 'Upload and monitor compliance documents for your vehicle.' }, settings: { icon: Settings2, title: 'Driver settings', description: 'Set operational alerts and accessibility preferences.' }, support: { icon: CircleHelp, title: 'Driver support', description: 'Contact operations for trip, vehicle, or payout assistance.' } }[section];
  const Icon = config.icon;
  return <div><PageHeading title={config.title} description={config.description} /><Card className={darkCard}><CardHeader><CardTitle className="flex items-center gap-2"><Icon className="size-4 text-emerald-400" /> {config.title}</CardTitle><CardDescription className="text-slate-400">Changes are saved to your driver workspace.</CardDescription></CardHeader><CardContent>{section === 'documents' ? <div className="space-y-3">{['Driving licence', 'Vehicle registration', 'Insurance certificate'].map((document) => <div key={document} className="flex items-center justify-between rounded-xl border border-white/10 p-3"><span className="text-sm font-bold">{document}</span><Badge variant="default">Verified</Badge></div>)}</div> : section === 'settings' ? <div className="space-y-3">{['Trip assignment alerts', 'Payout updates', 'Route deviation warning'].map((label) => <label key={label} className="flex items-center justify-between rounded-xl border border-white/10 p-3 text-sm font-bold"><span>{label}</span><input type="checkbox" defaultChecked className="size-4 accent-emerald-500" /></label>)}</div> : <form onSubmit={(event) => { event.preventDefault(); setSaved(true); }} className="space-y-4">{section === 'vehicle' ? <><label className="block text-xs font-bold text-slate-300">Registration number<input defaultValue="KA 05 EV 1284" className="mt-1.5 h-10 w-full rounded-lg border border-white/10 bg-slate-950 px-3 text-sm text-white outline-none focus:border-emerald-400" /></label><label className="block text-xs font-bold text-slate-300">Vehicle model<input defaultValue="Tata Tigor EV" className="mt-1.5 h-10 w-full rounded-lg border border-white/10 bg-slate-950 px-3 text-sm text-white outline-none focus:border-emerald-400" /></label></> : <><label className="block text-xs font-bold text-slate-300">Topic<select className="mt-1.5 h-10 w-full rounded-lg border border-white/10 bg-slate-950 px-3 text-sm text-white outline-none focus:border-emerald-400"><option>Trip assistance</option><option>Payment issue</option><option>Vehicle concern</option></select></label><label className="block text-xs font-bold text-slate-300">Message<textarea required rows={5} className="mt-1.5 w-full rounded-lg border border-white/10 bg-slate-950 p-3 text-sm text-white outline-none focus:border-emerald-400" placeholder="Describe what you need…" /></label></>}<Button type="submit">{section === 'support' ? <><Send className="size-4" /> Send request</> : 'Save changes'}</Button>{saved && <p role="status" className="rounded-lg bg-emerald-400/10 p-3 text-xs font-semibold text-emerald-400">Saved successfully. Operations will see the update.</p>}</form>}</CardContent></Card></div>;
}

type ManifestEntryView = {
  _id?: string;
  customer?: { name?: string };
  pickupStop?: { stopName?: string };
  status?: string;
};

export function DriverPassengersPage({ tripId }: { tripId: string }) {
  const { data: trip, isLoading, isError } = useDriverTrip(tripId);
  const manifest = (trip?.manifest || []) as ManifestEntryView[];
  return <div><PageHeading title="Assigned passengers" description={`Trip #${tripId.slice(-8).toUpperCase()}`} /><Card className={darkCard}><CardHeader><CardTitle className="flex items-center gap-2"><Users className="size-4 text-emerald-400" /> Passenger manifest</CardTitle><CardDescription className="text-slate-400">Use Current Trip to board, drop, or mark a no-show.</CardDescription></CardHeader><CardContent className="space-y-3">{isLoading ? <p className="text-sm text-slate-400">Loading manifest…</p> : isError ? <p className="text-sm text-red-400">Unable to load the passenger manifest.</p> : manifest.length ? manifest.map((entry, index) => <div key={entry._id || index} className="flex items-center gap-3 rounded-xl border border-white/10 p-3"><div className="flex size-9 items-center justify-center rounded-full bg-emerald-400/15 text-sm font-bold text-emerald-400">{entry.customer?.name?.slice(0, 1) || 'P'}</div><div className="flex-1"><p className="text-sm font-bold">{entry.customer?.name || 'Passenger'}</p><p className="text-xs text-slate-400">Pickup: {entry.pickupStop?.stopName || 'Assigned stop'}</p></div><Badge variant="outline" className="border-white/10 bg-white/5 text-slate-300">{entry.status || 'PENDING'}</Badge></div>) : <p className="text-sm text-slate-400">No passengers are assigned to this trip yet.</p>}</CardContent></Card></div>;
}
